name: recora
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  bloc: ^8.1.0
  copy_with_extension: ^4.0.4
  dartx: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.7.0
  movie_repository:
    path: packages/movie_repository
  recora_utils:
    path: packages/recora_utils

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.2
  copy_with_extension_gen: ^4.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

dependency_overrides:
  test_api: 0.4.16

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env

